"""empty message

Revision ID: 3c0e28bf0ef8
Revises: 
Create Date: 2017-04-24 08:13:10.887615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c0e28bf0ef8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('searchresult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vid_idd', sa.String(), nullable=True),
    sa.Column('vid_namee', sa.String(), nullable=True),
    sa.Column('vid_img', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('searchresult')
    # ### end Alembic commands ###
